[2024-07-04T02:48:45.808+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-04T02:48:45.856+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingestion_dag.download_data_task scheduled__2024-07-02T07:00:00+00:00 [queued]>
[2024-07-04T02:48:45.870+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingestion_dag.download_data_task scheduled__2024-07-02T07:00:00+00:00 [queued]>
[2024-07-04T02:48:45.870+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-04T02:48:45.908+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): download_data_task> on 2024-07-02 07:00:00+00:00
[2024-07-04T02:48:45.918+0000] {standard_task_runner.py:63} INFO - Started process 167 to run task
[2024-07-04T02:48:45.930+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ingestion_dag', 'download_data_task', 'scheduled__2024-07-02T07:00:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/store_raw_data_dag.py', '--cfg-path', '/tmp/tmpme8l0jcv']
[2024-07-04T02:48:45.936+0000] {standard_task_runner.py:91} INFO - Job 26: Subtask download_data_task
[2024-07-04T02:48:46.027+0000] {task_command.py:426} INFO - Running <TaskInstance: ingestion_dag.download_data_task scheduled__2024-07-02T07:00:00+00:00 [running]> on host a1f4c6255ab3
[2024-07-04T02:48:46.196+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingestion_dag' AIRFLOW_CTX_TASK_ID='download_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T07:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T07:00:00+00:00'
[2024-07-04T02:48:46.199+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-04T02:48:46.200+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-04T02:48:46.201+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: download_wildfire_data() missing 2 required positional arguments: 'fire_points_file' and 'fire_poly_file'
[2024-07-04T02:48:46.222+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=ingestion_dag, task_id=download_data_task, run_id=scheduled__2024-07-02T07:00:00+00:00, execution_date=20240702T070000, start_date=20240704T024845, end_date=20240704T024846
[2024-07-04T02:48:46.244+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 26 for task download_data_task (download_wildfire_data() missing 2 required positional arguments: 'fire_points_file' and 'fire_poly_file'; 167)
[2024-07-04T02:48:46.299+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-04T02:48:46.339+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-04T02:48:46.341+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
