[2024-07-10T00:17:58.508+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-10T00:17:58.535+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_transformation.pyspark_task manual__2024-07-10T00:17:45.997882+00:00 [queued]>
[2024-07-10T00:17:58.547+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_transformation.pyspark_task manual__2024-07-10T00:17:45.997882+00:00 [queued]>
[2024-07-10T00:17:58.548+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-10T00:17:58.567+0000] {taskinstance.py:2330} INFO - Executing <Task(DataprocSubmitJobOperator): pyspark_task> on 2024-07-10 00:17:45.997882+00:00
[2024-07-10T00:17:58.577+0000] {standard_task_runner.py:63} INFO - Started process 3607 to run task
[2024-07-10T00:17:58.582+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'test_transformation', 'pyspark_task', 'manual__2024-07-10T00:17:45.997882+00:00', '--job-id', '143', '--raw', '--subdir', 'DAGS_FOLDER/transformation_dag.py', '--cfg-path', '/tmp/tmpb_8o3v3i']
[2024-07-10T00:17:58.588+0000] {standard_task_runner.py:91} INFO - Job 143: Subtask pyspark_task
[2024-07-10T00:17:58.672+0000] {task_command.py:426} INFO - Running <TaskInstance: test_transformation.pyspark_task manual__2024-07-10T00:17:45.997882+00:00 [running]> on host ea9610d9d6e7
[2024-07-10T00:17:58.809+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_transformation' AIRFLOW_CTX_TASK_ID='pyspark_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-10T00:17:45.997882+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-10T00:17:45.997882+00:00'
[2024-07-10T00:17:58.812+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-10T00:17:58.812+0000] {dataproc.py:2553} INFO - Submitting job
[2024-07-10T00:17:58.814+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-07-10T00:17:58.815+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-07-10T00:17:58.816+0000] {base.py:84} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-07-10T00:17:58.995+0000] {dataproc.py:2565} INFO - Job 34a41dfd-936e-4a4f-890e-09e14007ecae submitted successfully.
[2024-07-10T00:17:59.015+0000] {dataproc.py:2600} INFO - Waiting for job 34a41dfd-936e-4a4f-890e-09e14007ecae to complete
[2024-07-10T00:18:29.203+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-10T00:18:29.217+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/google/cloud/operators/dataproc.py", line 2601, in execute
    self.hook.wait_for_job(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/google/common/hooks/base_google.py", line 528, in inner_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/google/cloud/hooks/dataproc.py", line 829, in wait_for_job
    raise AirflowException(f"Job failed:\n{job}")
airflow.exceptions.AirflowException: Job failed:
reference {
  project_id: "famous-muse-426921-s5"
  job_id: "34a41dfd-936e-4a4f-890e-09e14007ecae"
}
placement {
  cluster_name: "example-cluster"
  cluster_uuid: "b120ed89-8d98-49e3-8a65-c7d8e1bb68be"
}
pyspark_job {
  main_python_file_uri: "gs://de-zoomcamp-cchow-bucket/transformation.py"
  args: "--project_id=famous-muse-426921-s5"
  args: "--bucket=de-zoomcamp-cchow-bucket"
  jar_file_uris: "gs://de-zoomcamp-cchow-bucket/spark-bigquery-latest_2.12.jar"
}
status {
  state: ERROR
  details: "Google Cloud Dataproc Agent reports job failure. If logs are available, they can be found at:\nhttps://console.cloud.google.com/dataproc/jobs/34a41dfd-936e-4a4f-890e-09e14007ecae?project=famous-muse-426921-s5&region=us-west1\ngcloud dataproc jobs wait \'34a41dfd-936e-4a4f-890e-09e14007ecae\' --region \'us-west1\' --project \'famous-muse-426921-s5\'\nhttps://console.cloud.google.com/storage/browser/dataproc-staging-us-west1-735867942533-qmookup3/google-cloud-dataproc-metainfo/b120ed89-8d98-49e3-8a65-c7d8e1bb68be/jobs/34a41dfd-936e-4a4f-890e-09e14007ecae/\ngs://dataproc-staging-us-west1-735867942533-qmookup3/google-cloud-dataproc-metainfo/b120ed89-8d98-49e3-8a65-c7d8e1bb68be/jobs/34a41dfd-936e-4a4f-890e-09e14007ecae/driveroutput.*"
  state_start_time {
    seconds: 1720570705
    nanos: 865588000
  }
}
status_history {
  state: PENDING
  state_start_time {
    seconds: 1720570678
    nanos: 979374000
  }
}
status_history {
  state: SETUP_DONE
  state_start_time {
    seconds: 1720570679
    nanos: 8839000
  }
}
status_history {
  state: RUNNING
  state_start_time {
    seconds: 1720570679
    nanos: 233911000
  }
}
yarn_applications {
  name: "test"
  state: FINISHED
  progress: 1
  tracking_url: "http://example-cluster-m:8088/proxy/application_1720567886766_0006/"
}
driver_output_resource_uri: "gs://dataproc-staging-us-west1-735867942533-qmookup3/google-cloud-dataproc-metainfo/b120ed89-8d98-49e3-8a65-c7d8e1bb68be/jobs/34a41dfd-936e-4a4f-890e-09e14007ecae/driveroutput"
driver_control_files_uri: "gs://dataproc-staging-us-west1-735867942533-qmookup3/google-cloud-dataproc-metainfo/b120ed89-8d98-49e3-8a65-c7d8e1bb68be/jobs/34a41dfd-936e-4a4f-890e-09e14007ecae/"
job_uuid: "34a41dfd-936e-4a4f-890e-09e14007ecae"
done: true

[2024-07-10T00:18:29.225+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=test_transformation, task_id=pyspark_task, run_id=manual__2024-07-10T00:17:45.997882+00:00, execution_date=20240710T001745, start_date=20240710T001758, end_date=20240710T001829
[2024-07-10T00:18:29.243+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 143 for task pyspark_task (Job failed:
reference {
  project_id: "famous-muse-426921-s5"
  job_id: "34a41dfd-936e-4a4f-890e-09e14007ecae"
}
placement {
  cluster_name: "example-cluster"
  cluster_uuid: "b120ed89-8d98-49e3-8a65-c7d8e1bb68be"
}
pyspark_job {
  main_python_file_uri: "gs://de-zoomcamp-cchow-bucket/transformation.py"
  args: "--project_id=famous-muse-426921-s5"
  args: "--bucket=de-zoomcamp-cchow-bucket"
  jar_file_uris: "gs://de-zoomcamp-cchow-bucket/spark-bigquery-latest_2.12.jar"
}
status {
  state: ERROR
  details: "Google Cloud Dataproc Agent reports job failure. If logs are available, they can be found at:\nhttps://console.cloud.google.com/dataproc/jobs/34a41dfd-936e-4a4f-890e-09e14007ecae?project=famous-muse-426921-s5&region=us-west1\ngcloud dataproc jobs wait \'34a41dfd-936e-4a4f-890e-09e14007ecae\' --region \'us-west1\' --project \'famous-muse-426921-s5\'\nhttps://console.cloud.google.com/storage/browser/dataproc-staging-us-west1-735867942533-qmookup3/google-cloud-dataproc-metainfo/b120ed89-8d98-49e3-8a65-c7d8e1bb68be/jobs/34a41dfd-936e-4a4f-890e-09e14007ecae/\ngs://dataproc-staging-us-west1-735867942533-qmookup3/google-cloud-dataproc-metainfo/b120ed89-8d98-49e3-8a65-c7d8e1bb68be/jobs/34a41dfd-936e-4a4f-890e-09e14007ecae/driveroutput.*"
  state_start_time {
    seconds: 1720570705
    nanos: 865588000
  }
}
status_history {
  state: PENDING
  state_start_time {
    seconds: 1720570678
    nanos: 979374000
  }
}
status_history {
  state: SETUP_DONE
  state_start_time {
    seconds: 1720570679
    nanos: 8839000
  }
}
status_history {
  state: RUNNING
  state_start_time {
    seconds: 1720570679
    nanos: 233911000
  }
}
yarn_applications {
  name: "test"
  state: FINISHED
  progress: 1
  tracking_url: "http://example-cluster-m:8088/proxy/application_1720567886766_0006/"
}
driver_output_resource_uri: "gs://dataproc-staging-us-west1-735867942533-qmookup3/google-cloud-dataproc-metainfo/b120ed89-8d98-49e3-8a65-c7d8e1bb68be/jobs/34a41dfd-936e-4a4f-890e-09e14007ecae/driveroutput"
driver_control_files_uri: "gs://dataproc-staging-us-west1-735867942533-qmookup3/google-cloud-dataproc-metainfo/b120ed89-8d98-49e3-8a65-c7d8e1bb68be/jobs/34a41dfd-936e-4a4f-890e-09e14007ecae/"
job_uuid: "34a41dfd-936e-4a4f-890e-09e14007ecae"
done: true
; 3607)
[2024-07-10T00:18:29.262+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-10T00:18:29.287+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-10T00:18:29.290+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
