[2024-07-18T00:02:38.077+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-18T00:02:38.102+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fire_data_dag.load_fire_bq_task manual__2024-07-18T00:02:05.427891+00:00 [queued]>
[2024-07-18T00:02:38.116+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fire_data_dag.load_fire_bq_task manual__2024-07-18T00:02:05.427891+00:00 [queued]>
[2024-07-18T00:02:38.116+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-18T00:02:38.135+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): load_fire_bq_task> on 2024-07-18 00:02:05.427891+00:00
[2024-07-18T00:02:38.145+0000] {standard_task_runner.py:63} INFO - Started process 1502 to run task
[2024-07-18T00:02:38.151+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fire_data_dag', 'load_fire_bq_task', 'manual__2024-07-18T00:02:05.427891+00:00', '--job-id', '686', '--raw', '--subdir', 'DAGS_FOLDER/fire_data_dag.py', '--cfg-path', '/tmp/tmpc3o41pom']
[2024-07-18T00:02:38.153+0000] {standard_task_runner.py:91} INFO - Job 686: Subtask load_fire_bq_task
[2024-07-18T00:02:38.222+0000] {task_command.py:426} INFO - Running <TaskInstance: fire_data_dag.load_fire_bq_task manual__2024-07-18T00:02:05.427891+00:00 [running]> on host b83e2bee00d2
[2024-07-18T00:02:38.343+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fire_data_dag' AIRFLOW_CTX_TASK_ID='load_fire_bq_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-18T00:02:05.427891+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-18T00:02:05.427891+00:00'
[2024-07-18T00:02:38.346+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-18T00:02:38.347+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-18T00:02:38.348+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'bq load  --source_format=NEWLINE_DELIMITED_JSON --json_extension=GEOJSON --autodetect de_zoomcamp_cchow_dataset.wildfire_polygons_2 gs://de-zoomcamp-cchow-bucket/wildfire_polygons_nl.geojsonl']
[2024-07-18T00:02:38.369+0000] {subprocess.py:86} INFO - Output:
[2024-07-18T00:02:41.812+0000] {subprocess.py:93} INFO - BigQuery error in load operation: Error processing job 'famous-
[2024-07-18T00:02:41.813+0000] {subprocess.py:93} INFO - muse-426921-s5:bqjob_r46662851ff7b3acf_00000190c325ede6_1': Access Denied:
[2024-07-18T00:02:41.814+0000] {subprocess.py:93} INFO - BigQuery BigQuery: Missing required OAuth scope. Need BigQuery or Cloud Platform
[2024-07-18T00:02:41.814+0000] {subprocess.py:93} INFO - write scope.
[2024-07-18T00:02:42.107+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-07-18T00:02:42.108+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-18T00:02:42.125+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-07-18T00:02:42.133+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=fire_data_dag, task_id=load_fire_bq_task, run_id=manual__2024-07-18T00:02:05.427891+00:00, execution_date=20240718T000205, start_date=20240718T000238, end_date=20240718T000242
[2024-07-18T00:02:42.155+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 686 for task load_fire_bq_task (Bash command failed. The command returned a non-zero exit code 1.; 1502)
[2024-07-18T00:02:42.179+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-18T00:02:42.208+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-18T00:02:42.210+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
