[2024-07-09T22:39:41.573+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-09T22:39:41.598+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_transformation.pyspark_task manual__2024-07-09T22:39:30.266670+00:00 [queued]>
[2024-07-09T22:39:41.609+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_transformation.pyspark_task manual__2024-07-09T22:39:30.266670+00:00 [queued]>
[2024-07-09T22:39:41.609+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-09T22:39:41.629+0000] {taskinstance.py:2330} INFO - Executing <Task(DataprocSubmitJobOperator): pyspark_task> on 2024-07-09 22:39:30.266670+00:00
[2024-07-09T22:39:41.640+0000] {standard_task_runner.py:63} INFO - Started process 2094 to run task
[2024-07-09T22:39:41.646+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'test_transformation', 'pyspark_task', 'manual__2024-07-09T22:39:30.266670+00:00', '--job-id', '121', '--raw', '--subdir', 'DAGS_FOLDER/transformation_dag.py', '--cfg-path', '/tmp/tmp2r7f3ank']
[2024-07-09T22:39:41.651+0000] {standard_task_runner.py:91} INFO - Job 121: Subtask pyspark_task
[2024-07-09T22:39:41.728+0000] {task_command.py:426} INFO - Running <TaskInstance: test_transformation.pyspark_task manual__2024-07-09T22:39:30.266670+00:00 [running]> on host ea9610d9d6e7
[2024-07-09T22:39:41.864+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_transformation' AIRFLOW_CTX_TASK_ID='pyspark_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T22:39:30.266670+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-09T22:39:30.266670+00:00'
[2024-07-09T22:39:41.868+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-09T22:39:41.868+0000] {dataproc.py:2553} INFO - Submitting job
[2024-07-09T22:39:41.870+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-07-09T22:39:41.871+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-07-09T22:39:41.872+0000] {base.py:84} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-07-09T22:39:42.044+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-09T22:39:42.045+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/google/cloud/operators/dataproc.py", line 2555, in execute
    job_object = self.hook.submit_job(
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/google/common/hooks/base_google.py", line 528, in inner_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/google/cloud/hooks/dataproc.py", line 896, in submit_job
    return client.submit_job(
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/google/cloud/dataproc_v1/services/job_controller/client.py", line 772, in submit_job
    response = rpc(
               ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/home/airflow/.local/lib/python3.11/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/home/airflow/.local/lib/python3.11/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
             ^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ResourceExhausted: 429 No agent on master node(s) found to be active in the past 300 seconds.
Last reported times: [example-cluster-m seconds: 1720564251
nanos: 589865000
]. This may indicate high memory usage in Dataproc master or an unhealthy Dataproc master node
[2024-07-09T22:39:42.064+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=test_transformation, task_id=pyspark_task, run_id=manual__2024-07-09T22:39:30.266670+00:00, execution_date=20240709T223930, start_date=20240709T223941, end_date=20240709T223942
[2024-07-09T22:39:42.081+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 121 for task pyspark_task (429 No agent on master node(s) found to be active in the past 300 seconds.
Last reported times: [example-cluster-m seconds: 1720564251
nanos: 589865000
]. This may indicate high memory usage in Dataproc master or an unhealthy Dataproc master node; 2094)
[2024-07-09T22:39:42.099+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-09T22:39:42.126+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-09T22:39:42.128+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
