[2024-07-17T22:58:07.977+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-17T22:58:08.002+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fire_data_dag.load_fire_bq_task manual__2024-07-17T22:57:34.200682+00:00 [queued]>
[2024-07-17T22:58:08.018+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fire_data_dag.load_fire_bq_task manual__2024-07-17T22:57:34.200682+00:00 [queued]>
[2024-07-17T22:58:08.018+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-17T22:58:08.038+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_fire_bq_task> on 2024-07-17 22:57:34.200682+00:00
[2024-07-17T22:58:08.048+0000] {standard_task_runner.py:63} INFO - Started process 390 to run task
[2024-07-17T22:58:08.054+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fire_data_dag', 'load_fire_bq_task', 'manual__2024-07-17T22:57:34.200682+00:00', '--job-id', '614', '--raw', '--subdir', 'DAGS_FOLDER/fire_data_dag.py', '--cfg-path', '/tmp/tmpvrz1hea6']
[2024-07-17T22:58:08.056+0000] {standard_task_runner.py:91} INFO - Job 614: Subtask load_fire_bq_task
[2024-07-17T22:58:08.128+0000] {task_command.py:426} INFO - Running <TaskInstance: fire_data_dag.load_fire_bq_task manual__2024-07-17T22:57:34.200682+00:00 [running]> on host b83e2bee00d2
[2024-07-17T22:58:08.252+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fire_data_dag' AIRFLOW_CTX_TASK_ID='load_fire_bq_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-17T22:57:34.200682+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-17T22:57:34.200682+00:00'
[2024-07-17T22:58:08.255+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-17T22:58:08.320+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-17T22:58:08.321+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/bq_load.py", line 38, in load_bq
    job_config = bigquery.LoadJobConfig(
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/google/cloud/bigquery/job/load.py", line 56, in __init__
    super(LoadJobConfig, self).__init__("load", **kwargs)
  File "/home/airflow/.local/lib/python3.11/site-packages/google/cloud/bigquery/job/base.py", line 180, in __init__
    setattr(self, prop, val)
  File "/home/airflow/.local/lib/python3.11/site-packages/google/cloud/bigquery/job/base.py", line 188, in __setattr__
    super(_JobConfig, self).__setattr__(name, value)
  File "/home/airflow/.local/lib/python3.11/site-packages/google/cloud/bigquery/job/load.py", line 490, in schema
    [field.to_api_repr() for field in value],
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/google/cloud/bigquery/job/load.py", line 490, in <listcomp>
    [field.to_api_repr() for field in value],
     ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/google/cloud/bigquery/schema.py", line 353, in to_api_repr
    answer["fields"] = [f.to_api_repr() for f in self.fields]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/google/cloud/bigquery/schema.py", line 353, in <listcomp>
    answer["fields"] = [f.to_api_repr() for f in self.fields]
                        ^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'to_api_repr'
[2024-07-17T22:58:08.334+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=fire_data_dag, task_id=load_fire_bq_task, run_id=manual__2024-07-17T22:57:34.200682+00:00, execution_date=20240717T225734, start_date=20240717T225808, end_date=20240717T225808
[2024-07-17T22:58:08.353+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 614 for task load_fire_bq_task ('dict' object has no attribute 'to_api_repr'; 390)
[2024-07-17T22:58:08.388+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-17T22:58:08.413+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-17T22:58:08.415+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
